-- AlterTable
ALTER TABLE "Student" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "surname" DROP NOT NULL,
ALTER COLUMN "birth_day" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Tutor" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "surname" DROP NOT NULL,
ALTER COLUMN "birth_day" DROP NOT NULL,
ALTER COLUMN "start_date" DROP NOT NULL;
